spring.application.name=syncbeat-mainframe
#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Postgres-local
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/syncbeat}
spring.datasource.username=postgres
spring.datasource.password=postgres
#Server
server.port=${SERVER_PORT:8080}
#Auth
jwt.secret=${JWT_SECRET:defaultsecretkey123456789012345678901234567890}
# Redis-local
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
# Flyway
spring.flyway.enabled=${FLYWAY_ENABLED:false}
spring.flyway.baseline-on-migrate=true
#AWS
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:test}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}